### ISSUE TITLE
user data entry deleted after sending push notification

### ISSUE THREAD

**Issue by man2** [Smile-SA/node-pushserver#22]
is it supposed to be like that, or I'm doing something wrong with the server?

**Comment by marob** [comment]
no, it's not. Can you describe how to reproduce?

**Comment by man2** [comment]
I think this lines of code do the deleting of user devices
GCMPusher.js

var handleResults = function (results) {
    var idsToUpdate = [],
        idsToDelete = [];

    results.forEach(function (result) {
        if (!!result.registration_id) {
            idsToUpdate.push({from: result.token, to: result.registration_id});

        } else if (result.error === 'InvalidRegistration' || result.error === 'NotRegistered') {
            idsToDelete.push(result.token);
        }
    });

    if (idsToUpdate.length > 0) pushAssociations.updateTokens(idsToUpdate);
    if (idsToDelete.length > 0) pushAssociations.removeDevices(idsToDelete);
};

I want to push notification many times without having to register each time I want to send push notifications. Is that possible?

**Comment by xquantum** [comment]
@man2 how did you solve this problem? I'm facing the same issue.

**Comment by jmaquet** [comment]
I had the same issue, it was an apple certificate issue. The error message is not that clear but the issue didn't come from the server itself. I think, that the server was not able to send the notification (because of certificate issue) so it tried to remove the user but didn't succeed.
By memory before the deleting message i had a issue number, that issue number was the key.
