### ISSUE TITLE
Out of date NPM doc

### ISSUE THREAD

**Issue by andycampbell92** [Smile-SA/node-pushserver#30]
The doc for this on NPM is a little outdated it still references sqlite instead of mongoDB to store the user tokens. This makes for some strange errors if you are expecting it to use sqlite.

https://www.npmjs.com/package/node-pushserver

**Comment by marob** [comment]
Thanks for the information. In fact, it is the other way around: the future version of node-pushserver will use sqlite instead of mongoDB.
We've performed some "alpha" release tests on the npm registry, but as it is not yet stable, the latest version is still with mongoDB.

The problem is then that npm registry kept the README of the alpha version! I don't know why and don't know how to tell the registry to use the correct version of the README. For me, it seems to be a bug of the registry as it tells the latest version is 0.5.4 while displaying the 1.0.0-alpha.4 README...

https://github.com/npm/npm/issues/5259 seems to correspond to our problem.
