### ISSUE TITLE
ERROR: ValidationError: Validator "required" failed for path token with value `undefined`

### ISSUE THREAD

**Issue by alexbleks** [Smile-SA/node-pushserver#58]
I get this error when I try to subscribe a device.

![skjermbilde 2016-05-15 kl 13 48 56](https://cloud.githubusercontent.com/assets/17303226/15273807/021c37b8-1aa4-11e6-8267-e382577b2b87.png)

ERROR: ValidationError: Validator "required" failed for path token with value `undefined`, Validator "required" failed for path type with value `undefined`, Validator "required" failed for path user with value `undefined`

**Comment by marob** [comment]
There seems to be a problem in your code as the data is not present in the POST request.
You could check that the problem is in your code (and not in node-pushserver) with wireshark/tcpdump and see if user, type and token are present in the HTTP request.

As I'm not a PHP expert, I can't really help you solve your problem.

**Comment by alexbleks** [comment]
Aha, so what the error message basically says is that the POST fields are empty?

**Comment by alexbleks** [comment]
Figured it out, json_encode was set as "request".
